export { default as NewsBG } from './newsbg.png' 
export { default as WireKid } from './news_thumb.jpg'
export { default as RedApples } from './redapple.jpg'
export { default as TowerThumb } from './tower_thumb.jpg'
export { default as Violin } from './violin.png'